name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'

      - name: Pub Get Packages
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze
      
      - name: Run Flutter Test
        run: flutter test

      - name: Run Flutter Test Coverage
        run: flutter test --coverage

      - name: Convert lcov.info to html
        run: |
          apt-get update -qq -y
          apt-get install lcov -y
          genhtml coverage/lcov.info -o coverage/html

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash
        shell: bash

      - name: Build APPBUNDLE
        run: flutter build appbundle --release
