name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'

      - name: Pub Get Packages
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze
      
      - name: Run Flutter Test
        run: flutter test

      - name: Build APPBUNDLE
        run: flutter build appbundle --release

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          prerelease: true
          artifacts: "build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APPBUNDLE
          path: build/app/outputs/bundle/release/app-release.aab
